version: '3'

services:
    xilution-web-frontend-example:
        build: .
        container_name: xilution-web-frontend-example
        image: xilution/xilution-web-frontend-example
        ports:
            - '81:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
